site_name: ""
theme:
  name: material
  logo: assets/oixio_Digital_logo.png
  favicon: assets/oixio_Digital_logo.png
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.path
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      accent: custom

extra_css:
  - assets/extra.css

plugins:
  - search
  - i18n: # https://gitlab.com/mkdocs-i18n/mkdocs-i18n/-/blob/main/mkdocs.yml
      default_language: et
      languages:
        en: English
        et: Eesti keel
      translate_nav:
        en:
          home: "Home"
          bank_link: "Baltic Bank Connect"
          Lursoft: "Lursoft"
          Doc_links: "DocLink Manager"
          ItemRef: "Smart Item Codes"
          JobQueue: "Failed Queue Notifier"
          EE: "Reference Manager"
          RelatedItems: "Related Goods Manager"
          Units: "Alternative Units"
          Email: "Enhanced Email"
          Base: "CentralPlus"
          Attributes: "Advanced Item Attributes"
          XRoad: "XRoad"
          DigiSign: "DigiSign"
        et:
          home: "Pealeht"
          bank_link: "Baltic Bank Connect"
          Lursoft: "Lursoft"
          Doc_links: "DocLink Manager"
          ItemRef: "Smart Item Codes"
          JobQueue: "Failed Queue Notifier"
          EE: "Reference Manager"
          RelatedItems: "Related Goods Manager"
          Units: "Alternative Units"
          Email: "Enhanced Email"
          Base: "CentralPlus"
          Attributes: "Advanced Item Attributes"
          XRoad: "XRoad"
          DigiSign: "DigiSign"

extra:
  alternate:
    - name: Estonian
      link: /et/
      lang: et
    - name: English
      link: /en/
      lang: en
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/oixiodigital/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://oixio.eu/digital/"  target="_blank" rel="noopener">OIXIO Digital AS</a>

nav:
  - bank_link: banklink/banklink_index.et.md
  - bank_link: banklink/banklink_index.en.md
  - Lursoft: lursoft/lursoft_index.en.md
  - Lursoft: lursoft/lursoft_index.et.md
  - Doc_links: doc_links/doclinks_index.et.md
  - Doc_links: doc_links/doclinks_index.en.md
  - ItemRef: itemref/itemref_index.et.md
  - ItemRef: itemref/itemref_index.en.md
  - JobQueue: jobqueue/jobqueue_index.et.md
  - JobQueue: jobqueue/jobqueue_index.en.md
  - EE: ee/sunoee_index.et.md
  - EE: ee/sunoee_index.en.md
  - RelatedItems: relitems/relitems_index.et.md
  - RelatedItems: relitems/relitems_index.en.md
  - Units: units/units_index.et.md
  - Units: units/units_index.en.md
  - Email: email/email_index.et.md
  - Email: email/email_index.en.md
  - Base: base/base_index.et.md
  - Base: base/base_index.en.md
  - Attributes: attributes/attributes_index.et.md
  - Attributes: attributes/attributes_index.en.md
  - XRoad: xroad/xroad_index.et.md
  - XRoad: xroad/xroad_index.en.md
  - DigiSign: digisign/digisign_index.en.md
